### ISSUE TITLE
Would like to do exact searches

### ISSUE THREAD

**Issue by CrespoHP2** [bagbag/mediathekviewweb#10]
When searching for e.g. "Wüste", unprecise results like "Küste", "Büste", "Waste" etc are displayed, thus splattering my search results.
Imho searches should be more precise by default, unless stated by some kind of pattern/expression.

**Comment by bagbag** [comment]
I agree, that must be changed.

An other example: "!srf" basically only shows results from "orf".

**Comment by bagbag** [comment]
It's possible now: 4a4711c41813f801368211609d071021e36bb9b0

It will also do substring matches now (using [NGram Tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-ngram-tokenizer.html)), which makes it possible to find "schiff" in "dampfschiff" and also eliminates the flashing of results while typing.
