### ISSUE TITLE
index into separate index to allow background indexing

### ISSUE THREAD

**Issue by bagbag** [bagbag/mediathekviewweb#13]
hints:
- [reindex](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html)
- [alias](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html)
- ([rollover](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-rollover-index.html)?)

**Comment by bagbag** [comment]
As indexing description (for #21) consumes noticeably more time now (last index took 70 seconds), this gets more important.

**Comment by Wikinaut** [comment]
👍

**Comment by bagbag** [comment]
As my current server doesn't have enough RAM (I didn't tested it, but im pretty sure - its 2/3 used right now), I cannot implement that.

And as the contract is for a whole year... I have to postpone this (and/or look for another solution).

**Comment by bagbag** [comment]
solution found: delta-updates
