### ISSUE TITLE
Zugriff auf das Optionsmenü mit dem Firefox Browser [Android]

### ISSUE THREAD

**Issue by 0880** [bagbag/mediathekviewweb#16]
Auf dem Smartphone gibt es ein Problem mit dem Menü. Tippt man auf das Videosymbol ![Icon](https://cloud.githubusercontent.com/assets/11850160/21962134/5de15336-db1e-11e6-9e8a-9daf49d8d1ab.png)
öffnet sich sowohl der Player, als auch das Menü mit den verschiedenen Qualitätsstufen. Da beides gleichzeitig passiert, hat man keine Möglichkeit eine Aktion auszuwählen.

Getestet mit dem Firefox Browser für Android.

![Screenshot](https://cloud.githubusercontent.com/assets/11850160/21962132/46466f36-db1e-11e6-948b-659fd558accc.png)

**Comment by bagbag** [comment]
Dem Problem mit Touchscreens bin ich mir bewusst, doch musste ich abwägen zwischen Schnellstart für alle oder niemandem. Da jedoch der überwiegende Großteil der Nutzer die Seite per Desktop aufrufen, habe ich mich **bisher** für "Schnellstart für alle" entschieden.

Hintergrund: Es gibt keine zuverlässige Methode herauszufinden, ob es ein Gerät mit oder ohne Touchscreen ist.

Eine Möglichkeit, die mir gerade eingefallen ist das ganze halbwegs zu lösen: Doppel-, statt Einfach-Klick.

**Comment by 0880** [comment]
Wenn ich den Link zum Video kopieren will (um das Video mit einer anderen App abzuspielen), muss ich per [Long Tap](https://support.mozilla.org/en-US/kb/use-gestures-in-firefox-android#w_long-tap-for-more-options) das Videosymbol ![Icon](https://cloud.githubusercontent.com/assets/11850160/21962134/5de15336-db1e-11e6-9e8a-9daf49d8d1ab.png) antippen, um das Optionsmenü des Browsers zu öffnen. Dort kann ich dann auswählen: `Link-Adresse kopieren` oder `Mit App "Filme" öffnen`. Damit lässt sich nur eine Qualitätsstufe abspielen, obwohl mehrere verfügbar sind. Hab jetzt nochmal alles probiert. Das Menü der Webseite bleibt für mich auf dem Smartphone unerreichbar.

**Comment by bagbag** [comment]
Sollte nun möglich sein: 2e8f70294e19ea14c8e14ffee57c5a79572ef874

bitte feedback geben.

**Comment by 0880** [comment]
Es funktioniert! Ich kann jetzt auf das Menü zugreifen und eine Aktion auswählen. Danke!
Was sich zusätzlich noch verändert hat, ist die Ausrichtung der Größenangabe und die Anordnung der Icons. Das ist aber nicht weiter problematisch, da alles andere einwandfrei funktioniert!

![Screenshot](https://cloud.githubusercontent.com/assets/11850160/21996208/5ac87a92-dc29-11e6-80b3-1bdb1d2f147d.png)

**Comment by bagbag** [comment]
Auf kleinen Bildschirmen was das schon die ganze Zeit so.
Das gehe ich ein andermal an - evtl. mit einer komplett neuen Oberfläche.
