### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by 0880** [bagbag/mediathekviewweb#17]
Es wäre sinnvoll eine Subdomain / Weiterleitung einzurichten.

https://www.mediathekviewweb.de

```
Fehler: Server nicht gefunden

Der Server unter www.mediathekviewweb.de konnte nicht gefunden werden.
```

**Comment by bagbag** [comment]
Die Weiterleitung ist eingerichtet und funktioniert, jedoch habe ich gerade ein Problem das passende SSL-Zertifikat dafür zu bekommen, weshalb der Browser eine Fehlermeldung ausgibt. Ich werde es morgen noch einmal versuchen.

Ich danke die für den Hinweis :)

**Comment by bagbag** [comment]
Jetzt habe ich auch hierfür ein gültiges SSL-Zertifikat.
