### ISSUE TITLE
Add option to search everywhere including the description text

### ISSUE THREAD

**Issue by Wikinaut** [bagbag/mediathekviewweb#21]
Pls. add a further option to extend the search to the description text.

(BTW: Klasse Sache, das neue Tool. Where to donate ?)

**Comment by bagbag** [comment]
Good idea. I will implement that soon.

I don't need donations to keep the website running. The costs are below 10€ per month, which I can easily handle with my pocket money. That's why I haven't set up donations.

But if you wan't to "buy me a beer" (even though I don't like beer yet), leave me a mail at [kontakt@mediathekviewweb.de](mailto:kontakt@mediathekviewweb.de), then I will send you my address.

**Comment by bagbag** [comment]
Implemented: [https://mediathekviewweb.de/#query=*terror%2Canschlag](https://mediathekviewweb.de/#query=*terror%2Canschlag) returns every entry containing terror AND anschlag in its description.

**Comment by Wikinaut** [comment]
Does "not" work for me.... I tried with terms from the "description" - current version does not list items when searcherd with terms from the description text.

**Comment by Wikinaut** [comment]
Example:

Search term "walfang" or "walfänger" => 0 results

but present in description of http://www.3sat.de/mediathek/?mode=play&obj=64519 ("Meine Traumreise nach Kanada")

**Comment by bagbag** [comment]
Did you prepend a "*"?

![walfanger](https://cloud.githubusercontent.com/assets/4116942/22666594/777a59ee-ecb9-11e6-9824-97db8ed829e4.png)

**Comment by Wikinaut** [comment]
Nööö, hab ich nicht... No, I did not prepend. "works for me"-


May be that the future, the use of these prefixes might puzzle users, as "#" and "*" are well known regular expression meta characters...

Assume someone wants later to look for "phil*p glas*" or for "*fänger" (Tierfänger, Walfänger.....).

**Comment by bagbag** [comment]
the only alternative I came up with yet would be something like "c:ard t:tagesschau d:wahl" or multiple text fields.

But I dont like both. Do you got any better idea?

**Comment by Wikinaut** [comment]
Hmm, I understand. I will discuss it here.

`station:ard title:traumreise title:kanada all:walfang`
but this looks like an expert option. Indeed, it will puzzle users.

My original proposal here was, that you "simply" add a fourth option checkbox "Alle Felder" oder "Tiefe Suche"  oder "Irgendwo" (so heißt das in MediatheView"), die dann alle Worte des Eingabefelds "irgendwo" sucht. Ich finde dieses viel einfacher.

Also:

"walfang" => 0 results
"walfang" plus checkbox "everywhere" => n results


`Suche überall - Ähnliche Beiträge - Zukünftige Sendungen - Hilfe`

**Comment by bagbag** [comment]
"Ähnlich" gets removed (as said in your commit).

But now I need to decide how to implement "search everywhere". I have 2 possibilities for now:

Lets say we have:

channel: "ARD" | topic: "Sturm" | title: "der" | description: "Liebe"
channel: "ARD" | topic: "Sturm der Liebe" | title: "Folge 1000" | description: "blablabla"

Match first? Match second? Match both?

**Comment by Wikinaut** [comment]
"Search everywhere" =

prepend all parameters *without* an operator (internally) with `!#*`, I mean: search all terms, which are not prepended with an operator, in *all* fields.

**Comment by bagbag** [comment]
I also need a operator for title now. Any suggestion?

"!ard #sturm,der,liebe +folge,1000 *fürstenhof", '+' is the best I found yet.

**Comment by Wikinaut** [comment]
`+` may make problems in forms....
I would code it as follows:

* no prefix && search-everywhere off: search title
* no prefix && search-everywhere on: search everywhere

**Comment by bagbag** [comment]
current behavior when no prefix: search in title & topic. I don't wan't to change that (as it returns best results in most cases).

but now I wan't that if you search everywhere, that you can still limit entries for specific fields.
"sturm der liebe !ndr" with everywhere on should be limited to ndr..
"sturm der liebe +folge,1000" with everywhere on should return folge 1000 no matter if "sturm der liebe" is topic or title (depends on channel)

what you mean with forms?

**Comment by Wikinaut** [comment]
forms = `<input ...>`(what is sent to, and received by, your server).

In my view:
make a simple interface, and one for experts.

In MediathekView, I always and only use a quick & dirty input into the Thema/Title field. If I cannot find my result, I click onto "irgendwo". Basically, I want the same behaviour here with your MVW program (let's reset/restart the discussion to that).

As Mies van der Rohe (and others) said: "LESS IS MORE".....

**Comment by bagbag** [comment]
I don't use forms anywhere so that doesn't matter.

Uhm, its not simple enough? It cannot really be less than it is right now.

If you wanna go expert use !#*+

If you cannot find your wanted result, enable "Überall".

So what exactly you want to change?

**Comment by bagbag** [comment]
And btw: its implemented now: 1c28c8fb5021b70ee00867ffde785c24e6efdb80. Took me the whole evening.

**Comment by Wikinaut** [comment]
most likely 👍 👍 
thank you

BTW: this setting ("überall") should be saved in localStorage. I haven't checked whether it's already permanently saved, but in my view, it should be *sticky*.

**Comment by bagbag** [comment]
You're right. What I also want to add for some time is a selection for default quality - permanently saved.

**Comment by Wikinaut** [comment]
@bagbag wrote
> took me the whole evening

This is why I will sent you a donation next week.

**Comment by Wikinaut** [comment]
> default quality

👍

**Comment by Wikinaut** [comment]
but the saved (current) quality setting should be displayed when one comes to MVW

**Comment by bagbag** [comment]
Sure, I will not reject that :)

Yeah, I want to do it via a dropdown showing current setting. And to still have a clean layout, I think I will put it into a collapseable. As a single Item isn't enough, I'm forced to add more filtering (like by time, date, quality...).
