### ISSUE TITLE
[Suggestion] Direct download link url: add download attribute to <a href="video.mp4"> links

### ISSUE THREAD

**Issue by Wikinaut** [bagbag/mediathekviewweb#23]
I use Firefox, and was trying to find out why I don't see the "open as / save as" menu when clicking onto your download icons. This is according to https://support.mozilla.org/de/questions/1055477 based on (about:config) media.play-stand-alone (true).

As we cannot ask users to toggle this setting, I was trying to find a programmatic solution which fires a download dialog when clicking the Url.

According to https://stackoverflow.com/questions/20956434/create-download-link-for-music-or-video/20956558#20956558 and http://www.w3schools.com/tags/att_download.asp there is a `download` option attribute, which you can try in your code. (I cannot, because I haven't installed your server code at the moment).

> The download attribute specifies that the target will be downloaded when a user clicks on the hyperlink.
> This attribute is only used if the href attribute is set.

Perhaps you can try it on your server:
` <a href="video.mp4" download>`

**Comment by bagbag** [comment]
I'm using the download attribute already.

I've recently had that topic via E-Mail. Quote from myself (you are german, aren't you?):

> dass das mit dem Diskettensymbol nicht funktioniert ist leider eine Restriktion von Firefox. Der erlaubt das direkte Runterladen von Cross-Origin Ressourcen nicht. Unter Chrome funktioniert es. Ich kann da also leider nichts machen (zumindest ist mir keine Lösung dafür bekannt).

**Comment by Wikinaut** [comment]
Oh, yes. Cross origin will not work fro security reasons, of course. 
Suggestion to add a tooltip `"Right-click, then select "save target as" for downloading"`
