### ISSUE TITLE
Small GUI problem with "Description" tooltips: tooltips are not closed always

### ISSUE THREAD

**Issue by Wikinaut** [bagbag/mediathekviewweb#31]
I think, you will change the tooltip code later, or skip that description column as discussed in another issue, but I want to report a small issue with the current implementation.

A tooltip is not closed and stays visible when moving over it. 

#### How to reproduce:

* click onto the first description arrow down
* a first tooltip opens now
* now move the cursor (hover) **over** this first opened tooltip
* (notice, that now the tooltip does not close when moving out of the tooltip)
* click onto another description arrow down
* new tooltip opens and overlaps the first one.

This effect, the numerous opened tooltips, can currently only be cleared by reloading the page.

**Comment by bagbag** [comment]
I am aware of that problem but it's supposed to keep open while you hover over it.
The only thing that it shouldn't is keeping open when moving out of *it* **and** *the arrow*.

You can still close it then if you move your mouse over the arrow (and then **not** into the popover) or by clicking on it.

**Comment by Wikinaut** [comment]
Ah, now I understand. It was a feature, accepted! 

Perhaps you can add code, so that an opened tooltip can _also_be closed by clicking on it. Make sure, that it remains possible for users to mark and copy texts from the tooltip, which might be needed now and then.

Because the issue as such is solved, I close this issue. Thanks for your swift answer.
