### ISSUE TITLE
[Suggestion] Suppress unavailable videos in the view. Add an option (default=on) "Show only available videos".

### ISSUE THREAD

**Issue by Wikinaut** [bagbag/mediathekviewweb#32]
Example: search for "mord,mit,aussicht,4".
( http://www.ardmediathek.de/tv/Film-Serie-ONE/Mord-mit-Aussicht-4-39/ONE/Video?bcastId=27258646&documentId=40361414 )

Results in "0 Bytes" if you open the video download icon.

I suggest to suppress such entries (if this possible) by default in order not to spoil the list view with items you cannot play.

**Comment by bagbag** [comment]
As the Filesize is fetched server side (for caching) when hovering on it (to avoid useless requests), it's not possible with the current architecture (which has more pros than cons I think).

And as it is only a minority of videos, I'm fine with it.
