### ISSUE TITLE
usability-issue, nothing important but: icon for download 

### ISSUE THREAD

**Issue by taxiwriter** [bagbag/mediathekviewweb#33]
I would suggest to use the "get_app" Symbol from the "materials-icons" instead of "save" as symbol for download. The oldfassioned floppydisc icon looks nice and I like it, but today..?! Less and less people know w.t.f. a floppy is and what the symbol means. 
However, perhaps people who use this website, are old enough to know that Icon - ... like me ;)

**Comment by bagbag** [comment]
I like floppy disk more, even though I'm not from floppy disk times.

![get_app](https://cloud.githubusercontent.com/assets/4116942/22748721/454d43f0-ee2b-11e6-8ea1-cb55d76801df.png)
![save](https://cloud.githubusercontent.com/assets/4116942/22748725/46ab0e58-ee2b-11e6-85a9-cf5bc369835e.png)
