### ISSUE TITLE
when video is playing in fullscreen, esc should exit fullscreen instead of closing the video.

### ISSUE THREAD

**Issue by bagbag** [bagbag/mediathekviewweb#4]

**Comment by bagbag** [comment]
fa8d8b0e47e52be129d4948e70ec32057e85b528 fixed it.

If video is in fullscreen, esc exits it, otherwise it closes the video.

**Comment by claell** [comment]
I just tried this in Chrome and for me it still closes the complete video when pressing esc.

It works on Firefox, but after leaving fullscreen esc does not work to close the whole video.

**Comment by bagbag** [comment]
Have you reloaded the Page?
I'm developing with Chrome and it works fine for me. Just tested in Firefox... works.

**Comment by claell** [comment]
Yes I reloaded. The proplem still occurs for me. Maybe because I am on Linux (Ubuntu 16.10)?

**Comment by bagbag** [comment]
I'm also on Linux (Arch). What version of both Browsers do you have?

**Comment by claell** [comment]
I am using Chrome Version 54.0.2840.71 unknown (64-bit) and Firefox 50.1.0

**Comment by bagbag** [comment]
I've tested it now a few times and suddenly I got it to. Now I changed something: b58a305e303ba1388c294f9fda8139bc9f381ace
Would you please reload the page, try it and give feedback?

**Comment by claell** [comment]
Works now with Chrome and also on Firefox.

**Comment by bagbag** [comment]
Great. Thanks for telling me :)
