### ISSUE TITLE
Keine Verbindung

### ISSUE THREAD

**Issue by claell** [bagbag/mediathekviewweb#5]
Ich finde das Projekt interessant. Es ist ansprechender gestaltet und scheint mehr Funktionen als mediathekdirekt zu bieten. Leider kommt beim Aufruf der Seite immer nur Folgendes:

![bildschirmfoto vom 2016-12-30 15-57-31](https://cloud.githubusercontent.com/assets/6171135/21566977/bbe53b14-cea8-11e6-80db-973b26a96db7.png)

**Comment by claell** [comment]
Jetzt klappt es. Ist eventuell nur ein temporärer Fehler gewesen.

**Comment by bagbag** [comment]
Dieser Fehler trat auf, wenn das GUI erst nach dem Verbinden aufgebaut wurde, habe ich mit 34d9472fdfbf5c2d000a76186d548daec15ea2a2 gefixxt.

**Comment by claell** [comment]
Ah, danke fürs Beheben.
