### ISSUE TITLE
Leere Tabelle beim Start

### ISSUE THREAD

**Issue by claell** [bagbag/mediathekviewweb#6]
Wenn kein Suchbegriff eingegeben ist, steht bei mir "Keine Daten in der Tabelle vorhanden".

Ich fände es besser, wenn dann alle Dateien angezeigt würden.

**Comment by bagbag** [comment]
Alle eventuell nicht, das wäre mit momentan 170.000 Einträgen etwas viel, aber die aktuellsten 50 Stück (keine zukünftigen) hatte ich schon länger vor zu machen.

**Comment by bagbag** [comment]
Ist nun implementiert: ceb8f6532ff6e63a5aa3564cb86bdb0f38fbd44d

**Comment by claell** [comment]
Das ging ja schnell :smile:

**Comment by bagbag** [comment]
So solls sein :)
