### ISSUE TITLE
In Firefox wird das Video beim Maximieren oder Minimieren pausiert

### ISSUE THREAD

**Issue by claell** [bagbag/mediathekviewweb#7]
Beim Videoplayer von Firefox wird das Video aktuell leider immer pausiert, wenn man das Fenster maximiert oder minimiert.

**Comment by bagbag** [comment]
Sollte durch fa8d8b0e47e52be129d4948e70ec32057e85b528 nun hoffentlich behoben sein (bitte feedback geben).

**Comment by claell** [comment]
Ja, klappt jetzt!
